name: XDN Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm-proxy.fury.io/moovweb/
      - run: npm install
      - run: cat node_modules/react-storefront/package.json|grep 'version'
      - run: npm run deploy -- --apiKey=$XDN_DEPLOY_TOKEN
        env:
          CI: true
          XDN_DEPLOY_TOKEN: ${{secrets.XDN_DEPLOY_TOKEN}}
